// This file is auto-generated by Unity.
// To regenerate, open Unity and choose Spatial > Regenerate TypeScript Interface.
import { AppState } from "./models"

// prettier-ignore
export const emptyAppState: AppState = {
  "activeLoginMethod" : 0,
  "antiAliasing" : 0,
  "appFlags" : {
  },
  "appSessionID" : "",
  "appSessionNumber" : 0,
  "authToken" : "",
  "avatarSDK" : {
    "accessToken" : "",
    "tokenType" : ""
  },
  "bootStatus" : 0,
  "bootstrapTreatments" : {
    "forceAuthlessUserToLogin" : false,
    "promptAuthlessUserToLoginOnStart" : false,
    "useOVRLayersOnQuest" : false
  },
  "cameraPixelRatio" : 0,
  "cameraViewport" : {
    "animation" : {
      "curveType" : 4,
      "duration" : 0,
      "targetRect" : [
        0,
        0,
        1,
        1
      ]
    },
    "rect" : [
      0,
      0,
      1,
      1
    ]
  },
  "cast" : {
    "captureClientID" : "",
    "captureIP" : "",
    "captureUserID" : "",
    "lastViewPosition" : [
      0,
      0,
      0
    ],
    "lastViewRotation" : [
      0,
      0,
      0,
      0
    ],
    "lastViewScale" : [
      0,
      0,
      0
    ]
  },
  "clientVersion" : "",
  "clientVersionChannel" : "",
  "commitSHA" : "",
  "contentMetaDataCache" : {
  },
  "debug" : {
    "allowMultipleWebBrowsers" : false,
    "debugConsoleVisible" : false,
    "fpsThrottleMs" : 0,
    "logChannelFlags" : 0,
    "logLevel" : 0,
    "menuVisible" : false,
    "overlayStatsMode" : 0,
    "remoteLogChannelFlags" : 0,
    "remoteLogLevel" : 0
  },
  "environment" : {
    "ableToSwitchEnvironment" : false,
    "builtInLoadStatus" : 0,
    "customEnvironmentModelLoadStatus" : 0,
    "customEnvironmentSkyboxModelLoadStatus" : 0,
    "customNFTEnvironmentID" : "",
    "customNFTEnvironmentOptions" : {
    },
    "disableTeleport" : false,
    "enableFog" : false,
    "isEnvironmentLoaded" : false,
    "lastTeleportHotspot" : {
      "position" : [
        0,
        0,
        0
      ],
      "sitPosition" : [
        0,
        0,
        0
      ],
      "rotation" : [
        0,
        0,
        0,
        0
      ],
      "overrideOrientation" : false
    },
    "loadProgress" : 0,
    "loadStatus" : 0,
    "localAvatarFallingGravityMultiplier" : 0,
    "localAvatarGravityMultiplier" : 0,
    "localAvatarJumpHeight" : 0,
    "localAvatarMaxJumpCount" : 0,
    "localAvatarMovingSpeed" : 0,
    "localAvatarRunSpeed" : 0,
    "localAvatarUseVariableHeightJump" : false,
    "mainSurfaceAngle" : 0,
    "mainSurfaceBounds" : {
      "center" : [
        0,
        0,
        0
      ],
      "size" : [
        0,
        0,
        0
      ]
    },
    "mainSurfaceDotsVisible" : false,
    "mainSurfaceVisible" : false,
    "teleportHotSpots" : [
    ],
    "thumbnailCameraFOV" : 0,
    "thumbnailCameraPosition" : [
      0,
      0,
      0
    ],
    "thumbnailCameraRotation" : [
      0,
      0,
      0,
      0
    ],
    "type" : 7,
    "unityPackageLoadStatus" : 0
  },
  "featureFlags" : {
    "backpack" : false,
    "currentKey" : "",
    "firstQuestSpacePath" : "",
    "isFetching" : false,
    "isLoaded" : false,
    "isStale" : false,
    "liveExploreV2" : false,
    "loadedKey" : "",
    "showBadgesOnUserProfile" : false
  },
  "hasUsedMouseOrKeyboard" : false,
  "internetReachable" : false,
  "introStatus" : 0,
  "isAuthless" : false,
  "isLandscapeScreenOrientation" : false,
  "isLoadingRooms" : false,
  "isLoggedIn" : false,
  "isMouseInUnity" : false,
  "isTurnMenuOpen" : false,
  "itemMetadataCache" : {
  },
  "localAvatar" : {
    "attachmentItemIDs" : [
    ],
    "attachments" : {
    },
    "attachmentURLs" : [
    ],
    "avatarSDKAvatarID" : "",
    "avatarStyle" : 0,
    "body" : "",
    "isPreviewing" : false,
    "shirtColorOverride" : [
      0,
      0,
      0,
      0
    ],
    "skinColorOverride" : [
      0,
      0,
      0,
      0
    ]
  },
  "locationData" : {
    "city" : "",
    "countryCode" : "",
    "countryName" : "",
    "gpsLocation" : [
      0,
      0
    ],
    "regionCode" : "",
    "regionName" : ""
  },
  "loginCode" : "",
  "loginCodeSecret" : "",
  "loginHistoryUsers" : {
  },
  "loginStatus" : 0,
  "loginStatusMsg" : "",
  "maxAutoCameraPixelRatio" : 0,
  "microphone" : {
    "avgAmplitude" : 0,
    "gain" : 0,
    "peakAmplitude" : 0,
    "shouldRecord" : false,
    "source" : "",
    "status" : 0
  },
  "minAutoCameraPixelRatio" : 0,
  "perfStatistics" : {
    "droppedFrameCount" : 0,
    "fpsCount" : 0,
    "graphicsMemorySize" : 0,
    "graphicsMemoryUsage" : 0,
    "systemMemorySize" : 0,
    "systemMemoryUsage" : 0,
    "triangleCount" : 0,
    "vertexCount" : 0
  },
  "platform" : 0,
  "popupSystem" : {
    "currentGroupID" : 0,
    "currentPopupID" : 0,
    "groupIDCounter" : 0,
    "messageGroups" : {
    },
    "popupIDCounter" : 0
  },
  "promptAuthlessUserToLogin" : false,
  "rooms" : {
  },
  "roomSession" : {
    "abuseSafeguardsEnabled" : false,
    "actors" : {
    },
    "actorsLookup" : {
    },
    "addContentEnabled" : false,
    "administratorToolsActive" : false,
    "arSession" : {
      "isEnvironmentMeshingEnabled" : false,
      "worldAnchoringStatus" : 0
    },
    "avatarMovementEnabled" : false,
    "avatarOverride" : {
      "attachments" : {
      },
      "avatarStyle" : 0,
      "bodyURL" : "",
      "type" : 0
    },
    "avatarOverridePreview" : {
      "type" : 0,
      "avatarStyle" : 0,
      "bodyURL" : "",
      "attachments" : {
      }
    },
    "backpack" : {
      "hasNewItems" : false,
      "isInitialized" : false,
      "isOpen" : false,
      "items" : {
      },
      "itemsEnabledState" : {
      },
      "itemTypesEnabledState" : {
      },
      "pendingWorldCurrencyBalanceUpdates" : [
      ],
      "universalItemContinuationToken" : "",
      "worldCurrencyBalance" : 0,
      "worldCurrencyID" : "",
      "worldCurrencyName" : "",
      "worldCurrencyThumbnail" : "",
      "worldItemContinuationToken" : ""
    },
    "camera" : {
      "autoplayAvailableCount" : 0,
      "autoplayIndex" : 0,
      "autoplayProgress" : 0,
      "autoplayTargetObjectID" : 0,
      "isFirstPerson" : false,
      "isOrbitCamera" : false,
      "isStrafing" : false,
      "mode" : 0,
      "platformOffset" : [
        0,
        0,
        0
      ],
      "rotationMode" : 0
    },
    "cameraMovementEnabled" : false,
    "changeEnvironmentEnabled" : false,
    "clearRoomEnabled" : false,
    "clientCanAutosaveRoom" : false,
    "contentBrowser" : {
      "mode" : 0,
      "scrollPosition" : 0,
      "selectedIntegration" : 0
    },
    "creatorSocialProfile" : {
      "displayName" : "",
      "about" : "",
      "username" : "",
      "url" : "",
      "profilePictureURL" : "",
      "bannerSpaceID" : "",
      "bannerURL" : "",
      "usernameTwitter" : "",
      "usernameInstagram" : "",
      "usernameOpensea" : "",
      "usernameDiscord" : "",
      "usernameLinkedin" : "",
      "usernameTiktok" : "",
      "usernameFacebook" : "",
      "linkWebsite" : "",
      "numFollowers" : 0,
      "numFollowing" : 0,
      "numSpaces" : 0,
      "appearanceCustomization" : {
        "profileColor" : ""
      },
      "isPrivate" : false,
      "linkTwitter" : "",
      "linkInstagram" : "",
      "linkOpensea" : "",
      "linkDiscord" : "",
      "linkLinkedin" : "",
      "linkTiktok" : "",
      "linkFacebook" : ""
    },
    "customEnvironmentMeshTeleportAvailable" : false,
    "debug" : {
      "localLogOverrideEnabled" : false,
      "logChannelFlagsOverride" : 0,
      "logLevelOverride" : 0,
      "toolkitExternalErrorLogCount" : 0
    },
    "debugRTCStatistics" : "",
    "debugStatistics" : "",
    "debugVoiceStatistics" : "",
    "deleteContentEnabled" : false,
    "dock" : {
      "mobileTopPosition" : 0,
      "mode" : 0,
      "subDockMenu" : 0
    },
    "downloadContentEnabled" : false,
    "editAdminContentEnabled" : false,
    "editRoomNameEnabled" : false,
    "features" : [
    ],
    "initialDataLoadComplete" : false,
    "inputOverride" : {
      "flags" : 0
    },
    "inRoom" : false,
    "inRoomAndFullyParticipating" : false,
    "inRoomAndFullySynced" : false,
    "inSession" : false,
    "isAdministrator" : false,
    "isAuthlessInfoConfirmed" : false,
    "isAuthlessPrivateLobby" : false,
    "isChangeEnvironmentSettingAvailable" : false,
    "isChatOpen" : false,
    "isClearAllFramesAvailable" : false,
    "isCreatingSpace" : false,
    "isHideAllEmptyFramesAvailable" : false,
    "isHostInstance" : false,
    "isInitialEnvironmentLoadFinalized" : false,
    "isInitialRespawnComplete" : false,
    "isInitialRoomContentLoadComplete" : false,
    "isLeaving" : false,
    "isMasterClient" : false,
    "isMyLobby" : false,
    "isMyPrivateLobby" : false,
    "isReadOnlyActor" : false,
    "isRestrictedToViewOnly" : false,
    "isRoomOwner" : false,
    "itemPreview" : {
      "isLoading" : false,
      "itemID" : ""
    },
    "joinContext" : {
      "method" : 0
    },
    "lastDataLoadTime" : "0001-01-01T00:00:00.0000000",
    "lastRespawnOrientation" : [
      0,
      0,
      0,
      0
    ],
    "lastRespawnPosition" : [
      0,
      0,
      0
    ],
    "leaveReason" : 0,
    "lightBoxTargetObjectID" : 0,
    "loadTemplateEnabled" : false,
    "localActorInitialized" : false,
    "localActorNumber" : 0,
    "localAvatarObjectID" : 0,
    "localHideOverrides" : {
    },
    "localMuteOverrides" : {
    },
    "localUserIsSetup" : false,
    "localVideoPlayerStates" : {
    },
    "mainDockEnabled" : false,
    "mainWallEnabled" : false,
    "masterActorNumber" : 0,
    "meetingID" : "",
    "meetings" : [
    ],
    "memoryUsageMenuOpen" : false,
    "mobileJoystickActive" : false,
    "mobileJoystickVisible" : true,
    "moderation" : {
      "bannedModal" : {
        "bannedUntilUnixMillis" : 0,
        "visible" : false
      },
      "bannedUsers" : {
      },
      "targetUserID" : ""
    },
    "muteAnyoneEnabled" : false,
    "networkStrength" : 0,
    "objectIDToDirectURLLookup" : {
    },
    "offlineMode" : false,
    "participantChatDisabled" : false,
    "persistedStateIsDirty" : false,
    "persistenceStatus" : 0,
    "photonSessionID" : "",
    "portalDestinationsData" : {
      "deletedDestinations" : [
      ],
      "destinations" : {
      }
    },
    "preJoinedPhotonSessionID" : "",
    "profileMenuOpen" : false,
    "questSystem" : {
      "currentQuestID" : 0,
      "isInitializedFromUserSpaceState" : false,
      "isLoaded" : false,
      "isReady" : false,
      "quests" : {
      }
    },
    "retryingToJoin" : false,
    "retryJoinAttempts" : 0,
    "room" : {
      "id" : "",
      "ownerID" : "",
      "ownerName" : "",
      "name" : "",
      "slug" : "",
      "description" : "",
      "tags" : [
      ],
      "active" : false,
      "organizationOwnerID" : "",
      "organizationOwnerName" : "",
      "organizations" : [
      ],
      "shareSetting" : 0,
      "publicLink" : false,
      "isSandbox" : false,
      "isCreatorToolkitSpace" : false,
      "packageSKU" : "",
      "shareID" : "",
      "thumbnails" : [
      ],
      "participants" : {
      },
      "directlyInvitedGuests" : {
      },
      "version" : 0,
      "commitSHA" : "",
      "clientVersion" : "",
      "clientVersionChannel" : "",
      "starred" : false,
      "administrators" : [
      ],
      "restrictedPermissions" : [
      ],
      "sortPriority" : 0,
      "excludeFromMenus" : false,
      "accessible" : false,
      "transientThumbnailGetUrl" : "",
      "persistentThumbnailGetUrl" : "",
      "cubemapGetUrl" : "",
      "customThumbnailGetUrl" : "",
      "thumbnail" : "",
      "thumbnailsExpireAt" : 0,
      "roomCategories" : 0,
      "lobbyType" : 0,
      "tileSize" : 0,
      "isInstanceable" : false,
      "isNFTSpace" : false,
      "visitCount" : 0,
      "loveCount" : 0,
      "isLoved" : false,
      "isLive" : false,
      "lastLiveUnixMillis" : 0,
      "isPublishedToExplore" : false,
      "worldID" : ""
    },
    "roomContentLoadingSet" : [
    ],
    "roomID" : "",
    "roomModalType" : 0,
    "sandbox" : {
      "bundleURL" : "",
      "isMine" : false,
      "type" : 0
    },
    "saveAsTemplateEnabled" : false,
    "saveRoomEnabled" : false,
    "sceneHasEmptyGalleryFrames" : false,
    "screenshareEnabled" : false,
    "selectedObject" : {
      "inspector" : {
        "components" : [
        ]
      },
      "objectID" : 0,
      "transformManipulationMode" : 0
    },
    "sessionDataSynced" : false,
    "sessionID" : "",
    "sessionStatus" : 0,
    "settingsMenuVisible" : false,
    "sharedState" : {
      "actorLocationLookup" : {
      },
      "actorMetaData" : {
      },
      "actorsBroadcastingVideo" : [
      ],
      "customEnvironment" : {
        "animationClipName" : "",
        "animationStartTime" : "0001-01-01T00:00:00.0000000",
        "animationStatus" : 0,
        "customTransformSet" : false,
        "meshTeleportEnabled" : false,
        "modelFilePermission" : 0,
        "modelPivotMode" : 0,
        "modelPosition" : [
          0,
          0,
          0
        ],
        "modelRotation" : [
          0,
          0,
          0,
          0
        ],
        "modelsBeingSet" : {
        },
        "modelScale" : [
          0,
          0,
          0
        ],
        "modelSizingMode" : 0,
        "modelURL" : "",
        "skyboxFilePermission" : 0,
        "skyboxURL" : ""
      },
      "dataVersion" : 0,
      "environment" : {
        "builtIn" : {
          "type" : 7
        },
        "model" : {
        },
        "type" : 0,
        "unityPackage" : {
          "animators" : {
          },
          "outstandingSpatialEvents" : {
          },
          "sceneInitialized" : false,
          "sceneStateVersion" : 0,
          "url" : ""
        }
      },
      "loadingRoomTemplates" : {
      },
      "locations" : {
      },
      "meetingStartTime" : "0001-01-01T00:00:00.0000000",
      "scene" : {
        "attachedScribbles" : {
        },
        "audioPlayers" : {
        },
        "avatars" : {
        },
        "colliders" : {
        },
        "documents" : {
        },
        "embeddedObjects" : {
        },
        "galleryFrames" : {
        },
        "galleryInfos" : {
        },
        "galleryPedestals" : {
        },
        "hyperlinks" : {
        },
        "images" : {
        },
        "layoutByItem" : {
        },
        "layouts" : {
        },
        "mainWallObjectID" : 0,
        "mirrors" : {
        },
        "models" : {
        },
        "objects" : {
        },
        "pinnedObjects" : [
        ],
        "portals" : {
        },
        "prefabObjects" : {
        },
        "rigidbodies" : {
        },
        "rtcFeeds" : {
        },
        "scribbles" : {
        },
        "selfieStick" : {
        },
        "spawnPoints" : {
        },
        "speechCaptions" : {
        },
        "stickyNotes" : {
        },
        "surfaces" : {
        },
        "syncedVariables" : {
        },
        "thoughtflows" : {
        },
        "titles" : {
        },
        "transforms" : {
        },
        "videoPlayers" : {
        },
        "webBrowsers" : {
        },
        "whiteboards" : {
        }
      },
      "settings" : {
        "areEmptyGalleryFramesHidden" : false,
        "disableTeleportation" : false,
        "disableTextureCompressionForEnvironment" : false,
        "disableTextureCompressionForObjects" : false,
        "enableAudioAttenuation" : false,
        "enableAutosave" : false,
        "environment" : 7,
        "environmentChangerID" : "",
        "environmentVariant" : {
        },
        "useVariableSyncRate" : false,
        "voiceAppID" : "",
        "voiceLocationGroupingMethod" : 0,
        "voiceProvider" : 0
      },
      "syncedActors" : [
      ]
    },
    "sharePanelEnabled" : false,
    "shop" : {
      "isInitialized" : false,
      "isOpen" : false,
      "items" : {
      },
      "itemsDisplayStatus" : {
      }
    },
    "shouldBeConnectedToRTC" : false,
    "shouldShowLoadingScreen" : false,
    "showAllAvatars" : false,
    "socialProfileMenu" : {
      "followers" : [
      ],
      "followersListIsComplete" : false,
      "followersLoadStatus" : 0,
      "followings" : [
      ],
      "followingsListIsComplete" : false,
      "followingsLoadStatus" : 0,
      "menuVisible" : false,
      "profile" : {
        "displayName" : "",
        "about" : "",
        "username" : "",
        "url" : "",
        "profilePictureURL" : "",
        "bannerSpaceID" : "",
        "bannerURL" : "",
        "usernameTwitter" : "",
        "usernameInstagram" : "",
        "usernameOpensea" : "",
        "usernameDiscord" : "",
        "usernameLinkedin" : "",
        "usernameTiktok" : "",
        "usernameFacebook" : "",
        "linkWebsite" : "",
        "numFollowers" : 0,
        "numFollowing" : 0,
        "numSpaces" : 0,
        "appearanceCustomization" : {
          "profileColor" : ""
        },
        "isPrivate" : false,
        "linkTwitter" : "",
        "linkInstagram" : "",
        "linkOpensea" : "",
        "linkDiscord" : "",
        "linkLinkedin" : "",
        "linkTiktok" : "",
        "linkFacebook" : ""
      },
      "profileFollowPanelVisibility" : 0,
      "profileLoadStatus" : 0,
      "profilePageVisible" : false,
      "selectedUserID" : "",
      "selectedUserIsAuthless" : false,
      "spaces" : [
      ],
      "spacesLoadStatus" : 0
    },
    "speechCaptioningAvailable" : false,
    "statusMsg" : "",
    "subDockEnabled" : false,
    "sync" : {
      "isConnected" : false,
      "isConnectedAndSynced" : false
    },
    "syncRateMultiplier" : 0,
    "timeOfRoomSessionSynced" : 0,
    "uploadTargetFrameObjectID" : 0,
    "userSpaceState" : {
      "isLoaded" : false,
      "questSystem" : {
        "quests" : {
        }
      }
    },
    "userTeleportEnabled" : false,
    "userTools" : {
      "activeTool" : 0,
      "assetSharingTool" : {
        "assetURL" : ""
      },
      "customEnvironmentTool" : {
        "currentStep" : 0,
        "deleteModelIfCanceled" : false,
        "hideUI" : false,
        "usePreviousEnvTransform" : false
      },
      "manipulatingObjectIDs" : [
      ],
      "scribble" : {
        "brushSize" : 0,
        "color" : [
          0,
          0,
          0,
          0
        ],
        "lineID" : 0
      },
      "spacePortalToolState" : {
        "category" : 0,
        "searchTerm" : ""
      },
      "stickyNote" : {
        "mode" : 0
      },
      "targetObjectID" : 0,
      "thoughtflow" : {
        "mode" : 0
      },
      "useTransformGizmos" : false,
      "webBrowser" : {
        "mode" : 0
      },
      "whiteboard" : {
        "brushColor" : [
          0,
          0,
          0,
          0
        ],
        "brushSize" : 0,
        "hand" : 0,
        "inDrawZone" : false,
        "orientation" : [
          0,
          0,
          0,
          0
        ],
        "position" : [
          0,
          0,
          0
        ]
      }
    },
    "voice" : {
      "activeProvider" : 0,
      "isConnected" : false,
      "isMuted" : false,
      "isTalking" : false,
      "listeningToActors" : [
      ],
      "liveSwitch" : {
        "listeningToClients" : [
        ]
      },
      "photon" : {
        "actors" : {
        },
        "appID" : "",
        "connectionStatus" : 14,
        "isWebReadyForConnection" : false,
        "localVoiceActorNumber" : 0,
        "masterVoiceActorNumber" : 0
      },
      "shouldBeConnected" : false,
      "transmissionActive" : false,
      "transmissionEnabled" : false,
      "userEnabledVoiceConnection" : false
    },
    "webcamEnabled" : false,
    "webglCursorMode" : 0
  },
  "roomsMenu" : {
    "mode" : 0,
    "roomCategory" : 0,
    "roomSearchText" : ""
  },
  "rtc" : {
    "channelClaimed" : false,
    "channelConnectionStatus" : 0,
    "channelID" : "",
    "clientID" : "",
    "localMedias" : {
    },
    "mcuLayout" : {
    },
    "remoteClients" : {
    },
    "token" : "",
    "voiceUpstreamStats" : {
      "prevBytesSent" : 0,
      "prevFramesSent" : 0,
      "totalBytesSent" : 0,
      "totalFramesSent" : 0
    }
  },
  "sapiOrigin" : "",
  "sapiStatus" : 0,
  "screenOrientation" : 0,
  "showRatePopup" : false,
  "spatialUID" : "",
  "speechCaptionConfig" : {
    "availableLanguages" : [
    ],
    "enabled" : false,
    "languageCode" : ""
  },
  "startupMessage" : {
    "forceExit" : false,
    "message" : ""
  },
  "suppressLobbyAutoJoin" : false,
  "swagOrigin" : "",
  "targetFrameRate" : 0,
  "templates" : [
  ],
  "toastSystem" : {
    "maxToastCount" : 0,
    "toasts" : {
    }
  },
  "tutorial" : {
    "disableUserDock" : false,
    "disableUserTeleport" : false,
    "isConciseMode" : false,
    "status" : 0
  },
  "updateAvailabilityStatus" : 0,
  "useAutoCameraPixelRatio" : false,
  "userContent" : {
    "contentByID" : {
    },
    "contentByQuery" : {
    }
  },
  "userProfile" : {
    "acceptedEarlyAccessTerms" : false,
    "acceptedPrivacyPolicy" : false,
    "acceptedSept2022PrivacyPolicy" : false,
    "acceptedSept2022StandardTerms" : false,
    "acceptedStandardTerms" : false,
    "accountCompletionStatus" : "",
    "acknowledgedInAppNotificationKeys" : [
    ],
    "appearanceCustomization" : {
      "profileColor" : ""
    },
    "avatar" : {
      "activeAvatarStyle" : 0,
      "attachmentItemIDs" : [
      ],
      "attachments" : {
      },
      "avatarUserID" : "",
      "body" : "",
      "finalAvatarSDKID" : "",
      "finalBody" : "",
      "finalShirtColorOverride" : [
        0,
        0,
        0,
        0
      ],
      "finalSkinColorOverride" : [
        0,
        0,
        0,
        0
      ],
      "id" : "",
      "readyPlayerMeThumbnails" : {
        "lowerBody" : "",
        "upperBody" : ""
      },
      "readyPlayerMeUrl" : "",
      "shirtColorOverride" : [
        0,
        0,
        0,
        0
      ],
      "skinColorOverride" : [
        0,
        0,
        0,
        0
      ]
    },
    "blockedUsers" : [
    ],
    "config" : {
      "activePhotonConfigIndex" : 0,
      "activePhotonVoiceConfigIndex" : 0,
      "liveSwitch" : {
        "appID" : "",
        "url" : ""
      },
      "photonConfigs" : [
      ],
      "photonVoiceConfigs" : [
      ],
      "treatments" : {
        "animatedModelResizeBakingEnabled" : false,
        "audioPlayerEnabled" : false,
        "authlessPrivateLobbyFeatures" : [
        ],
        "autoPixelRatioMaxDimension" : 0,
        "autoPixelRatioOnlyClampsDimensions" : false,
        "autosaveDelay" : 0,
        "availableIntegrations" : [
        ],
        "avatarRTCFeedOpenDistance" : 0,
        "avProExcludedRoomIDs" : [
        ],
        "bringUsersToMeHostTool" : false,
        "customEnvBlocksLowerPriorityLoaders" : false,
        "customReflectionDisabledRoomIDs" : [
        ],
        "customReflectionEnabled" : false,
        "customReflectionEnabledRoomIDs" : [
        ],
        "debugMenu" : false,
        "emotesEnabled" : false,
        "fullSettingsMenu" : false,
        "hardcodedRespawnLogicRoomIDs" : [
        ],
        "hideInfoPanelSquaredDistance" : 0,
        "hlsMinVideoLength" : 0,
        "hmdContinousMovementEnabled" : false,
        "hmdTunnelingVignetteEnabled" : false,
        "hyperlinksV2" : false,
        "isModifiedCameraControllerEnabled" : false,
        "isModifiedCharacterControllerEnabled" : false,
        "liveSwitchEnabledRoomIDs" : [
        ],
        "localPhotonDebugLogs" : false,
        "maxAllowedRoomParticipants" : 0,
        "maxImageSize" : 0,
        "maxLoadersToAddPerFrame" : 0,
        "maxTextureSize" : 0,
        "maxTextureSizeCustomEnv" : 0,
        "maxTextureSizeSkybox" : 0,
        "mediaViewDebug" : false,
        "meshColliderVertexLimit" : 0,
        "minAudioTimeSyncThreshold" : 0,
        "minVideoTimeSyncThreshold" : 0,
        "mobileJoystickEnabled" : false,
        "mobilePortraitJoystickEnabled" : false,
        "nftAddressOverride" : "",
        "objectInspectorDebug" : false,
        "oculusSubscriptions" : false,
        "photonPluginType" : "",
        "photonVoiceBitrateOverride" : 0,
        "photonVoiceSamplingRateOverride" : 0,
        "privateLobbyPresetContent" : "",
        "progressiveModelLoading" : 0,
        "progressiveModelLoadingEnvironment" : 0,
        "readyPlayerMeDefaultBodies" : [
        ],
        "readyPlayerMeDefaultBodyFemale" : "",
        "readyPlayerMeDefaultBodyMale" : "",
        "recordReactBridgeTraces" : false,
        "remoteUnityLogLevel" : 0,
        "sendUsersToSeatsHostTool" : false,
        "showMobileStoreReviewInApp" : false,
        "showSyncedLocalAvatar" : false,
        "spaceContentLoadOrder" : 0,
        "thumbnailCaptureRoomContentLoadTimeout" : 0,
        "unlimitedFileSize" : false,
        "unthrottleContentLoadingWebGL" : false,
        "unthrottledGLTFastFrameBudgetHighPriorityWebGL" : 0,
        "unthrottledGLTFastFrameBudgetWebGL" : 0,
        "unthrottledLoaderIntervalWebGL" : 0,
        "unthrottledMaxActiveLoadersWebGL" : 0,
        "useCompressedModelsV1" : false,
        "useModelCollidersOnBoneTransform" : false,
        "userTeleportHostTool" : false,
        "videoPlayerPlugin" : 0,
        "voiceLocationGroupingMethod" : 0,
        "voiceProvider" : 0,
        "youTube" : false
      }
    },
    "displayName" : "",
    "editProfileResponseError" : {
      "code" : "",
      "error" : "",
      "field" : "",
      "message" : "",
      "statusCode" : 0
    },
    "editProfileResponseStatus" : 0,
    "email" : "",
    "followers" : [
    ],
    "followings" : [
    ],
    "integrations" : {
    },
    "isOnboardingRequired" : false,
    "myOrganization" : {
      "id" : "",
      "name" : ""
    },
    "organizations" : [
    ],
    "permissions" : [
    ],
    "preferences" : {
      "hmdLocomotionMode" : 0,
      "isLeftHanded" : false,
      "scribbleBrushColor" : [
        0,
        0,
        0,
        0
      ],
      "scribbleBrushSize" : 0,
      "searchMode" : 0,
      "stickyNoteColor" : [
        0,
        0,
        0,
        0
      ],
      "whiteboardBrushColor" : [
        0,
        0,
        0,
        0
      ],
      "whiteboardBrushSize" : 0
    },
    "profilePicURL" : "",
    "showEarlyAccessTerms" : false,
    "socialProfile" : {
      "about" : "",
      "appearanceCustomization" : {
        "profileColor" : ""
      },
      "bannerSpaceID" : "",
      "bannerURL" : "",
      "displayName" : "",
      "isPrivate" : false,
      "linkDiscord" : "",
      "linkFacebook" : "",
      "linkInstagram" : "",
      "linkLinkedin" : "",
      "linkOpensea" : "",
      "linkTiktok" : "",
      "linkTwitter" : "",
      "linkWebsite" : "",
      "numFollowers" : 0,
      "numFollowing" : 0,
      "numSpaces" : 0,
      "profilePictureURL" : "",
      "url" : "",
      "username" : "",
      "usernameDiscord" : "",
      "usernameFacebook" : "",
      "usernameInstagram" : "",
      "usernameLinkedin" : "",
      "usernameOpensea" : "",
      "usernameTiktok" : "",
      "usernameTwitter" : ""
    },
    "subscription" : {
      "isActive" : false,
      "subscriptionSource" : 0,
      "subscriptionType" : 0
    },
    "userID" : "",
    "walletAddresses" : {
    }
  },
  "userSessionNumber" : 0,
  "vSyncCount" : 0,
  "windowHasFocus" : false,
  "windowIsVisible" : false
}
